### ISSUE TITLE
Configurate to Firebase

### ISSUE THREAD

**Issue by madera-design** [BrightCoders-Institute/proyecto-final-rn-teama#15]
```[tasklist]
### Tasks
- [ ] Create DB in the Firebase
- [ ] Configure DB in the app
- [ ] Create a collection in the DB 
```
