### ISSUE TITLE
Edit-Profile-Employ-and-Employed

### ISSUE THREAD

**Issue by ShadowEnchanter** [BrightCoders-Institute/proyecto-final-rn-teama#23]
```[tasklist]
### Tasks
- [ ] Implement Redux
- [ ] Implement Edit Profile Employ Section
- [ ] Implement Edit Profile Employed Section
- [ ] Add Screen into Navigation
```
