### ISSUE TITLE
Implement-Redux-Data-User-Employed

### ISSUE THREAD

**Issue by ShadowEnchanter** [BrightCoders-Institute/proyecto-final-rn-teama#24]
## REQUIREMENTS / DESCRIPTION

```[tasklist]
### Tasks
- [ ] Configure Variable Redux
- [ ] Implement Redux for navigation data employed
- [ ] Implement Firebase for save data employed
```
