### ISSUE TITLE
Implement-Redux-Data-User-Employ

### ISSUE THREAD

**Issue by ShadowEnchanter** [BrightCoders-Institute/proyecto-final-rn-teama#25]
## REQUIREMENTS / DESCRIPTION

```[tasklist]
### Tasks
- [x] Configure Variable Redux
- [x] Implement Redux for navigation data employ
- [x] Add Screen "TellAboutYouScreens" and components
- [x] Modified Styles "ButtonNext"
- [x] Install package Firebase Storage for Upload Images
```

**Comment by ShadowEnchanter** [comment]
> ## REQUIREMENTS / DESCRIPTION
> ### Tasks
> 
> Beta
> [Give feedback](https://github.com/community/community/discussions/39106)
> 
> 1. [ ] 
>                  Configure Variable Redux
>                
>    
>                
>                  
>                    Configure Variable Redux
>    
>                  
>                    Configure Variable Redux
>                
>              
>    
>    
>    
>          
>            
>      
>        
>          
>        
>    
>      Options
>    
>    
>    
>      
>        
>          
>            
>      
>          * Convert to issue
>          * Toggle completion
>          * Rename
>          * Remove
>      
>    
>    
>      
>          
>          
>            
>              
>        
>    
>            
>            Successfully updated the issue's project
>          
>          
>            
>              
>        
>    
>            
>            There was an error updating the issue's project
> 2. [ ] 
>                  Implement Redux for navigation data employ
>                
>    
>                
>                  
>                    Implement Redux for navigation data employ
>    
>                  
>                    Implement Redux for navigation data employ
>                
>              
>    
>    
>    
>          
>            
>      
>        
>          
>        
>    
>      Options
>    
>    
>    
>      
>        
>          
>            
>      
>          * Convert to issue
>          * Toggle completion
>          * Rename
>          * Remove
>      
>    
>    
>      
>          
>          
>            
>              
>        
>    
>            
>            Successfully updated the issue's project
>          
>          
>            
>              
>        
>    
>            
>            There was an error updating the issue's project
> 3. [ ] 
>                  Add Screen "TellAboutYouScreens" and components
>                
>    
>                
>                  
>                    Add Screen "TellAboutYouScreens" and components
>    
>                  
>                    Add Screen "TellAboutYouScreens" and components
>                
>              
>    
>    
>    
>          
>            
>      
>        
>          
>        
>    
>      Options
>    
>    
>    
>      
>        
>          
>            
>      
>          * Convert to issue
>          * Toggle completion
>          * Rename
>          * Remove
>      
>    
>    
>      
>          
>          
>            
>              
>        
>    
>            
>            Successfully updated the issue's project
>          
>          
>            
>              
>        
>    
>            
>            There was an error updating the issue's project
> 4. [ ] 
>                  Modified Styles "ButtonNext"
>                
>    
>                
>                  
>                    Modified Styles "ButtonNext"
>    
>                  
>                    Modified Styles "ButtonNext"
>                
>              
>    
>    
>    
>          
>            
>      
>        
>          
>        
>    
>      Options
>    
>    
>    
>      
>        
>          
>            
>      
>          * Convert to issue
>          * Toggle completion
>          * Rename
>          * Remove
>      
>    
>    
>      
>          
>          
>            
>              
>        
>    
>            
>            Successfully updated the issue's project
>          
>          
>            
>              
>        
>    
>            
>            There was an error updating the issue's project
> 5. [ ] 
>                  Install package Firebase Storage for Upload Images
>                
>    
>                
>                  
>                    Install package Firebase Storage for Upload Images
>    
>                  
>                    Install package Firebase Storage for Upload Images
>                
>              
>    
>    
>    
>          
>            
>      
>        
>          
>        
>    
>      Options
>    
>    
>    
>      
>        
>          
>            
>      
>          * Convert to issue
>          * Toggle completion
>          * Rename
>          * Remove
>      
>    
>    
>      
>          
>          
>            
>              
>        
>    
>            
>            Successfully updated the issue's project
>          
>          
>            
>              
>        
>    
>            
>            There was an error updating the issue's project
> 6. [ ] 
>                    
>                  
>    
>                  
>                    
>                      
>    
>                    
>                      
>                  
>                
>                
>                  
>      
>        
>          
>        
>    
>      Options
>    
>    
>    
>      
>        
>          
>            
>      
>          * Convert to issue
>          * Toggle completion
>          * Rename
>          * Remove
> 7.
