### ISSUE TITLE
Login & SignUp Screens

### ISSUE THREAD

**Issue by ecruz17** [BrightCoders-Institute/proyecto-final-rn-teama#5]
```[tasklist]
### Tasks
- [ ] Design for Login Screen
- [ ] Design for Employee Signup Screen
- [ ] Design for Employer Signup Screen
```
![imagen](https://github.com/BrightCoders-Institute/proyecto-final-rn-teama/assets/47923715/3f8c4800-8699-4917-b88c-34d51ef9d4cf)
