### ISSUE TITLE
Home Screen Design 

### ISSUE THREAD

**Issue by ecruz17** [BrightCoders-Institute/proyecto-final-rn-teama#6]
```[tasklist]
### Tasks
- [ ] Create Tinder like carousel
- [ ] Create Dropdown component
- [ ] Create quick filters component
- [ ] Create like or dislike buttons
```
